[2021-09-29 14:11:44,078] {processor.py:162} INFO - Started process (PID=4256) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:11:44,080] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:11:44,081] {logging_mixin.py:109} INFO - [2021-09-29 14:11:44,081] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:11:44,101] {logging_mixin.py:109} INFO - [2021-09-29 14:11:44,099] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 40, in <module>
    python_callable=_print_log_messages,
NameError: name '_print_log_messages' is not defined
[2021-09-29 14:11:44,104] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:11:44,121] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.046 seconds
[2021-09-29 14:11:52,090] {processor.py:162} INFO - Started process (PID=4272) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:11:52,092] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:11:52,093] {logging_mixin.py:109} INFO - [2021-09-29 14:11:52,093] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:11:52,123] {logging_mixin.py:109} INFO - [2021-09-29 14:11:52,121] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 40, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:11:52,125] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:11:52,145] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.059 seconds
[2021-09-29 14:12:22,540] {processor.py:162} INFO - Started process (PID=4474) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:22,542] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:12:22,544] {logging_mixin.py:109} INFO - [2021-09-29 14:12:22,544] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:22,584] {logging_mixin.py:109} INFO - [2021-09-29 14:12:22,582] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 40, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:12:22,587] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:22,612] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.076 seconds
[2021-09-29 14:12:30,796] {processor.py:162} INFO - Started process (PID=4494) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:30,798] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:12:30,800] {logging_mixin.py:109} INFO - [2021-09-29 14:12:30,800] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:30,831] {logging_mixin.py:109} INFO - [2021-09-29 14:12:30,828] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 40, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:12:30,833] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:30,857] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.066 seconds
[2021-09-29 14:12:36,762] {processor.py:162} INFO - Started process (PID=4565) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:36,764] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:12:36,766] {logging_mixin.py:109} INFO - [2021-09-29 14:12:36,765] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:36,795] {logging_mixin.py:109} INFO - [2021-09-29 14:12:36,793] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 40, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:12:36,798] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:12:36,818] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.062 seconds
[2021-09-29 14:13:07,068] {processor.py:162} INFO - Started process (PID=4757) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:07,070] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:13:07,072] {logging_mixin.py:109} INFO - [2021-09-29 14:13:07,071] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:07,092] {logging_mixin.py:109} INFO - [2021-09-29 14:13:07,089] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 40, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:13:07,094] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:07,115] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.051 seconds
[2021-09-29 14:13:37,537] {processor.py:162} INFO - Started process (PID=4958) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:37,539] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:13:37,541] {logging_mixin.py:109} INFO - [2021-09-29 14:13:37,541] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:37,562] {logging_mixin.py:109} INFO - [2021-09-29 14:13:37,560] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 40, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:13:37,564] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:37,583] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.051 seconds
[2021-09-29 14:13:39,478] {processor.py:162} INFO - Started process (PID=5023) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:39,481] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:13:39,482] {logging_mixin.py:109} INFO - [2021-09-29 14:13:39,482] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:39,512] {logging_mixin.py:109} INFO - [2021-09-29 14:13:39,510] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 43, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:13:39,516] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:39,537] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.064 seconds
[2021-09-29 14:13:46,979] {processor.py:162} INFO - Started process (PID=5074) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:46,982] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:13:46,984] {logging_mixin.py:109} INFO - [2021-09-29 14:13:46,983] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:47,014] {logging_mixin.py:109} INFO - [2021-09-29 14:13:47,012] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 43, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:13:47,017] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:47,039] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.064 seconds
[2021-09-29 14:13:58,083] {processor.py:162} INFO - Started process (PID=5094) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:58,085] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:13:58,087] {logging_mixin.py:109} INFO - [2021-09-29 14:13:58,086] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:58,113] {logging_mixin.py:109} INFO - [2021-09-29 14:13:58,111] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 43, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:13:58,115] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:58,136] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.058 seconds
[2021-09-29 14:13:59,159] {processor.py:162} INFO - Started process (PID=5099) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:59,161] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:13:59,162] {logging_mixin.py:109} INFO - [2021-09-29 14:13:59,162] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:59,190] {logging_mixin.py:109} INFO - [2021-09-29 14:13:59,188] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 43, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:13:59,192] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:13:59,214] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.060 seconds
[2021-09-29 14:14:01,257] {processor.py:162} INFO - Started process (PID=5109) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:14:01,259] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:14:01,260] {logging_mixin.py:109} INFO - [2021-09-29 14:14:01,260] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:14:01,292] {logging_mixin.py:109} INFO - [2021-09-29 14:14:01,290] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 42, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:14:01,295] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:14:01,316] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.064 seconds
[2021-09-29 14:14:31,535] {processor.py:162} INFO - Started process (PID=5313) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:14:31,538] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:14:31,540] {logging_mixin.py:109} INFO - [2021-09-29 14:14:31,540] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:14:31,567] {logging_mixin.py:109} INFO - [2021-09-29 14:14:31,563] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 42, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:14:31,570] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:14:31,596] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.068 seconds
[2021-09-29 14:15:01,929] {processor.py:162} INFO - Started process (PID=5506) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:01,932] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:15:01,934] {logging_mixin.py:109} INFO - [2021-09-29 14:15:01,934] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:01,956] {logging_mixin.py:109} INFO - [2021-09-29 14:15:01,954] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 42, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:15:01,971] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:01,996] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.071 seconds
[2021-09-29 14:15:21,141] {processor.py:162} INFO - Started process (PID=5689) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:21,144] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:15:21,146] {logging_mixin.py:109} INFO - [2021-09-29 14:15:21,146] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:21,173] {logging_mixin.py:109} INFO - [2021-09-29 14:15:21,171] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 42, in <module>
    python_callable=print_log_messages,
NameError: name 'print_log_messages' is not defined
[2021-09-29 14:15:21,175] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:21,195] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.058 seconds
[2021-09-29 14:15:27,253] {processor.py:162} INFO - Started process (PID=5699) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:27,255] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:15:27,257] {logging_mixin.py:109} INFO - [2021-09-29 14:15:27,257] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:27,294] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:15:31,809] {logging_mixin.py:109} INFO - [2021-09-29 14:15:31,808] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:15:31,821] {logging_mixin.py:109} INFO - [2021-09-29 14:15:31,820] {dag.py:1853} INFO - Creating ORM DAG for homework_2_dag
[2021-09-29 14:15:31,831] {logging_mixin.py:109} INFO - [2021-09-29 14:15:31,831] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:15:31,848] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 4.599 seconds
[2021-09-29 14:16:02,876] {processor.py:162} INFO - Started process (PID=5925) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:16:02,878] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:16:02,879] {logging_mixin.py:109} INFO - [2021-09-29 14:16:02,879] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:16:02,901] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:16:02,923] {logging_mixin.py:109} INFO - [2021-09-29 14:16:02,923] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:16:02,943] {logging_mixin.py:109} INFO - [2021-09-29 14:16:02,943] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:16:02,955] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.082 seconds
[2021-09-29 14:16:33,890] {processor.py:162} INFO - Started process (PID=6118) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:16:33,899] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:16:33,902] {logging_mixin.py:109} INFO - [2021-09-29 14:16:33,902] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:16:33,943] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:16:33,973] {logging_mixin.py:109} INFO - [2021-09-29 14:16:33,973] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:16:33,998] {logging_mixin.py:109} INFO - [2021-09-29 14:16:33,998] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:16:34,025] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.140 seconds
[2021-09-29 14:17:04,289] {processor.py:162} INFO - Started process (PID=6322) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:04,292] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:17:04,294] {logging_mixin.py:109} INFO - [2021-09-29 14:17:04,294] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:04,319] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:04,349] {logging_mixin.py:109} INFO - [2021-09-29 14:17:04,348] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:17:04,373] {logging_mixin.py:109} INFO - [2021-09-29 14:17:04,373] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:17:04,388] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.102 seconds
[2021-09-29 14:17:34,785] {processor.py:162} INFO - Started process (PID=6513) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:34,787] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:17:34,789] {logging_mixin.py:109} INFO - [2021-09-29 14:17:34,788] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:34,816] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:34,845] {logging_mixin.py:109} INFO - [2021-09-29 14:17:34,845] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:17:34,869] {logging_mixin.py:109} INFO - [2021-09-29 14:17:34,869] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:17:34,883] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.102 seconds
[2021-09-29 14:17:39,667] {processor.py:162} INFO - Started process (PID=6559) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:39,669] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:17:39,671] {logging_mixin.py:109} INFO - [2021-09-29 14:17:39,671] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:39,682] {logging_mixin.py:109} INFO - [2021-09-29 14:17:39,680] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 48
    start >> echo_hello, say_hello, print_log_messages] >> end
                                                      ^
SyntaxError: invalid syntax
[2021-09-29 14:17:39,685] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:39,712] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.049 seconds
[2021-09-29 14:17:42,458] {processor.py:162} INFO - Started process (PID=6629) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:42,459] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:17:42,461] {logging_mixin.py:109} INFO - [2021-09-29 14:17:42,461] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:42,470] {logging_mixin.py:109} INFO - [2021-09-29 14:17:42,469] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 48
    start >> echo_hello >> say_hello, print_log_messages] >> end
                                                        ^
SyntaxError: invalid syntax
[2021-09-29 14:17:42,473] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:42,492] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.038 seconds
[2021-09-29 14:17:44,474] {processor.py:162} INFO - Started process (PID=6634) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:44,476] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:17:44,477] {logging_mixin.py:109} INFO - [2021-09-29 14:17:44,477] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:44,521] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:44,701] {logging_mixin.py:109} INFO - [2021-09-29 14:17:44,701] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:17:44,725] {logging_mixin.py:109} INFO - [2021-09-29 14:17:44,725] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:17:44,749] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.277 seconds
[2021-09-29 14:17:47,491] {processor.py:162} INFO - Started process (PID=6699) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:47,496] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:17:47,498] {logging_mixin.py:109} INFO - [2021-09-29 14:17:47,498] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:47,531] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:17:47,552] {logging_mixin.py:109} INFO - [2021-09-29 14:17:47,552] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:17:47,579] {logging_mixin.py:109} INFO - [2021-09-29 14:17:47,579] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:17:47,596] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.108 seconds
[2021-09-29 14:18:15,952] {processor.py:162} INFO - Started process (PID=6900) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:16,000] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:18:16,002] {logging_mixin.py:109} INFO - [2021-09-29 14:18:16,001] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:16,013] {logging_mixin.py:109} INFO - [2021-09-29 14:18:16,012] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/homework_2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/homework_2_dag.py", line 48
    [start >> echo_hello >> say_hello >> print_log_messages >> end
                                                                 ^
SyntaxError: unexpected EOF while parsing
[2021-09-29 14:18:16,015] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:16,034] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.088 seconds
[2021-09-29 14:18:17,985] {processor.py:162} INFO - Started process (PID=6907) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:17,987] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:18:17,989] {logging_mixin.py:109} INFO - [2021-09-29 14:18:17,988] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:18,020] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:18,204] {logging_mixin.py:109} INFO - [2021-09-29 14:18:18,203] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:18:18,219] {logging_mixin.py:109} INFO - [2021-09-29 14:18:18,219] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:18:18,233] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.251 seconds
[2021-09-29 14:18:48,273] {processor.py:162} INFO - Started process (PID=7111) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:48,276] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:18:48,277] {logging_mixin.py:109} INFO - [2021-09-29 14:18:48,277] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:48,308] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:18:48,334] {logging_mixin.py:109} INFO - [2021-09-29 14:18:48,334] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:18:48,355] {logging_mixin.py:109} INFO - [2021-09-29 14:18:48,355] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:18:48,365] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.096 seconds
[2021-09-29 14:19:18,575] {processor.py:162} INFO - Started process (PID=7303) to work on /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:19:18,577] {processor.py:613} INFO - Processing file /opt/airflow/dags/homework_2_dag.py for tasks to queue
[2021-09-29 14:19:18,578] {logging_mixin.py:109} INFO - [2021-09-29 14:19:18,578] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:19:18,607] {processor.py:623} INFO - DAG(s) dict_keys(['homework_2_dag']) retrieved from /opt/airflow/dags/homework_2_dag.py
[2021-09-29 14:19:18,637] {logging_mixin.py:109} INFO - [2021-09-29 14:19:18,637] {dag.py:1834} INFO - Sync 1 DAGs
[2021-09-29 14:19:18,662] {logging_mixin.py:109} INFO - [2021-09-29 14:19:18,661] {dag.py:2287} INFO - Setting next_dagrun for homework_2_dag to 2021-09-29T13:30:00+00:00
[2021-09-29 14:19:18,674] {processor.py:170} INFO - Processing /opt/airflow/dags/homework_2_dag.py took 0.104 seconds
